version: "2"
output:
  formats:
    text:
      path: stdout
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 60
      statements: 40
    govet:
      disable:
        - fieldalignment
      enable-all: true
    nestif:
      min-complexity: 4
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new-from-rev: origin/master
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
